spring:
  application:
    name: bookstore-api
  
  threads:
    virtual:
      enabled: true
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bookstore}
    username: ${DB_USERNAME:bookstore}
    password: ${DB_PASSWORD:bookstore}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:30}
      minimum-idle: ${DB_MIN_IDLE:10}
      connection-timeout: 2000
      idle-timeout: 30000
      max-lifetime: 600000
      leak-detection-threshold: 5000
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
    open-in-view: false
    show-sql: false
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,readiness,liveness
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLED:true}

app:
  security:
    admin:
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
    user:
      username: ${USER_USERNAME:user}
      password: ${USER_PASSWORD:user123}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.bookstore: ${APP_LOG_LEVEL:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
  pattern:
    console: "%d{ISO8601} %-5level [%X{traceId}] %c{1.} - %msg%n"