server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: false
  
  liquibase:
    enabled: false

app:
  security:
    admin:
      username: admin
      password: admin123
    user:
      username: user
      password: user123

logging:
  level:
    com.bookstore: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"